spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/courseinfo?serverTimezone=GMT%2B8
    username: root
    password: 52582320797lml
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #指向数据库管理系统 Specify the DBMS
    database: MYSQL
    #显示执行的sql语句 Show or not log for each sql query
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    #设置数据库引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


